#!/usr/bin/env node
const argv = require('yargs')
	.usage('Usage: $0 <command> [options]')
	// .command('get    <node> [rel] [child]', 'Get a node or pattern', require('./commands/get'))
	// .command('set    <node> [rel] [child]', 'Set a node or pattern', require('./commands/set'))
	// .command('unset  <node>', 'Unset node\'s label or property', require('./commands/unset'))
	// .command('change <old node> <new node>', "Change node's name", require('./commands/change'))
	// .command('delete <node>', "Delete a node", require('./commands/delete'))
	// .command('graph  <node>', "Show a node's graph", require('./commands/graph'))
	.command('user <email> <password>', "Show user", require('./commands/user'))
	.command('register <email> <password> [username]', "Register a user", require('./commands/register'))
	.command('connect <domain> <email> <password>', "Connect to domain", require('./commands/connect'))
	.command('create <domain> <email> <password>', "Create a domain", require('./commands/create'))
	.command('domains <email> <password>', "Show domains", require('./commands/show'))
	.count('verbose')
	.alias('v', 'verbose')
	.demandCommand(1)
  .argv
